### ISSUE TITLE
Enhancement: Allow self-signed certificates

### ISSUE THREAD

**Issue by larsl-net** [OneUptime/oneuptime#1248]
**Is your feature request related to a problem? Please describe.**
Currently, I try to add a Website Monitor for a service which uses a self-signed certificate.

**Describe the solution you'd like**
A way to add my root ca.

**Describe alternatives you've considered**
An option to disable TLS verification.

**Additional context**
I use the self-hosted docker-compose stack.

**Comment by 0xtan3** [comment]
Hi @larsl-net,

If you installed OneUptime using npm, you can update the docker-compose.yml file to add the required configuration.

Please add the following to the relevant services, such as **app**, **probe**, and possibly **ai-agent**:

```
app:
  image: oneuptime/app:${APP_TAG}
  extends:
    file: ./docker-compose.base.yml
    service: app
  extra_hosts:
    - "hosted-site:host-gateway"
  environment:
    - NODE_EXTRA_CA_CERTS=/usr/src/rootCA.crt
  volumes:
    - ./rootCA.crt:/usr/src/rootCA.crt:ro

```

You can apply the same configuration to any other service that needs to connect to the hosted site using the custom CA certificate.
