### ISSUE TITLE
Bad redirect for HTTP OTLP endpoint

### ISSUE THREAD

**Issue by golyalpha** [OneUptime/oneuptime#1749]
**Describe the bug**
When submitting telemetry over HTTP/otlp, there is a bad redirect to port 7849

**To Reproduce**
1. Deploy oneuptime from helm
2. Attempt to send telemetry over HTTPS (using the `/otlp` endpoint)
3. Watch as no telemetry is received
4. See redirects in nginx logs - sending a request to the endpoint URL results in a redirect to http @ 7849

**Expected behavior**
Telemetry is received properly

**Deployment Type**
Selfhosted

**Additional context**
curl log:
```
> curl -vL https://your.domain.com/otlp
* Host your.domain.com:443 was resolved.
* IPv6: (none)
* IPv4: 192.168.1.127
*   Trying 192.168.1.127:443...
* Connected to your.domain.com (192.168.1.127) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.x
> GET /otlp HTTP/1.1
> Host: your.domain.com
> User-Agent: curl/8.9.1
> Accept: */*
>
* Request completely sent off
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 18 Nov 2024 10:23:21 GMT
< Content-Type: text/html
< Content-Length: 169
< Connection: keep-alive
< Location: http://your.domain.com:7849/otlp/
< Strict-Transport-Security: max-age=31536000; includeSubDomains
* Ignoring the response-body
```

helm values.yml
```yml
host: your.domain.com

httpProtocol: https

oneuptimeSecret: "REDACTED"
encryptionSecret: "REDACTED"

nginx:
  service:
    type: ClusterIP

oneuptimeIngress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
  - your.domain.com
  tls:
    enabled: true
    hosts:
    - host: your.domain.com
      secretName: oneuptime-tls

image:
   tag: "7.0.3242"

postgresql:
  image:
    tag: 16.1.0-debian-11-r25

clickhouse:
  image:
    tag: 22.3.18-debian-11-r4  # I know this is old, 23+ builds crash with SIGILL

redis:
  image:
    tag: 7.2.4-debian-12-r9
```
